name: tm351vm-example
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - nano
  - postgresql
  - psycopg2
  - graphviz
  - openjdk
  - pyproj
  #- jupyter-server-proxy
  - pip:
    - git+https://github.com/innovationOUtside/ou-tm351-py.git
