#!/bin/bash
set -eux

echo "Running postBuild setup...."

BINDER_DIR=.binder

#Set up postgres
echo "Set-up postgres..."

PGDATA=${PGDATA:-${CONDA_DIR}/srv/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

#Copy the initialisation files into the final container
mv init_db $CONDA_DIR/
chmod +x $CONDA_DIR/init_db/postgres/init_db.sh
$CONDA_DIR/init_db/postgres/init_db.sh
#Put an equivalent of the above in a config file: init_db.sql
#psql -U postgres postgres -f init_db.sql
#psql test < seed_db.sql

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" stop

#Set up mongodb
echo "Set up mongo...."

MONGODB_VERSION=$(<.mongo_version) #4.2.8 #3.6.15
MONGODB_PATH=${CONDA_DIR}/srv/mongodb-$MONGODB_VERSION
MONGODB_BASE=mongodb-linux-x86_64-ubuntu1804 #mongodb-linux-x86_64

#https://fastdl.mongodb.org/linux/${MONGODB_BASE}-3.6.15.tgz
#wget -q https://fastdl.mongodb.org/linux/${MONGODB_BASE}-${MONGODB_VERSION}.tgz
# Should we detect the Linux version?
wget -q https://fastdl.mongodb.org/linux/${MONGODB_BASE}-${MONGODB_VERSION}.tgz

tar -xvf ${MONGODB_BASE}-${MONGODB_VERSION}.tgz >/dev/null
rm ${MONGODB_BASE}-${MONGODB_VERSION}.tgz
mv ${MONGODB_BASE}-${MONGODB_VERSION} ${MONGODB_PATH}

mkdir ${MONGODB_PATH}/data/db -p

#Seed mongodb
#${MONGODB_PATH}/bin/mongod --dbpath ${MONGODB_PATH}/data/db &
${MONGODB_PATH}/bin/mongod --fork --logpath /dev/stdout --dbpath ${MONGODB_PATH}/data/db

mkdir -p ./tmpdatafiles
tar xvjf ./data/small_accidents.tar.bz2 -C ./tmpdatafiles
${MONGODB_PATH}/bin/mongorestore --drop --db accidents ./tmpdatafiles/small_accidents
${MONGODB_PATH}/bin/mongod --shutdown --dbpath ${MONGODB_PATH}/data/db

rm -r ./data
rm -r ./tmpdatafiles

#Set up OpenRefine
echo "Set up OpenRefine..."
OPENREFINE_VERSION=$(<.openrefine_version)  #2.8
#wget -q -O openrefine-${OPENREFINE_VERSION}.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/${OPENREFINE_VERSION}/openrefine-linux-${OPENREFINE_VERSION}.tar.gz
wget -q -O openrefine-${OPENREFINE_VERSION}.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/${OPENREFINE_VERSION}/openrefine-linux-${OPENREFINE_VERSION}.tar.gz
mkdir -p $CONDA_DIR/openrefine
tar xzf openrefine-${OPENREFINE_VERSION}.tar.gz -C $CONDA_DIR/openrefine
rm openrefine-${OPENREFINE_VERSION}.tar.gz




#Although located in binder/,
# this bash file runs in $HOME rather than $HOME/.binder
mv .jupyter $CONDA_DIR/

#echo "Enable Jupyter server proxy extension..."
#Enable the server-proxy extension installed via conda;
# this lets us proxy OpenRefine and will
# enable the OpenRefine icon in JuptyerLab desktop launcher
# "ValueError: This extension does not yet support the current version of JupyterLab."
# I have no f****g idea...
#jupyter labextension install jupyterlab-server-proxy


echo "Install Python requirements..."

#Some Python package pre-requirements
#pip install --no-cache-dir numpy
#pip install --no-cache-dir scipy

#Python requirements
pip install --no-cache-dir -r ${BINDER_DIR}/requirements.txt

#Other requirements

#Need to tidy up after installing this?
git clone https://github.com/uclixnjupyternbaccessibility/accessibility_toolbar.git

#Install and enable extensions
echo "Enable Jupyter extensions..."

# TO DO - we should probably check that a package is installed before we try to install it?

jupyter nbextension install accessibility_toolbar --sys-prefix

jupyter contrib nbextension install --sys-prefix

#Enable certain extensions from the start
jupyter nbextension enable freeze/main --sys-prefix
jupyter nbextension enable highlighter/highlighter --sys-prefix
jupyter nbextension enable spellchecker/main --sys-prefix
jupyter nbextension enable collapsible_headings/main --sys-prefix
jupyter nbextension enable codefolding/main --sys-prefix
jupyter nbextension enable rubberband/main --sys-prefix
jupyter nbextension enable exercise2/main --sys-prefix
jupyter nbextension enable python-markdown/main --sys-prefix
jupyter nbextension enable export_embedded/main --sys-prefix

jupyter nbextension enable skip-traceback/main --sys-prefix
jupyter nbextension enable hide_input/main --sys-prefix
jupyter nbextension enable init_cell/main --sys-prefix

#Accessibility
jupyter nbextension install accessibility_toolbar --sys-prefix

# Explicit installation may not be required?
#jupyter nbextension install --user --py jupyter_nbrequirements

# AW: don't enable, but want to keep it installed
# Can always let students know it's there.
#jupyter nbextension enable accessibility_toolbar/main

#Slideshow
jupyter nbextension install rise  --py --sys-prefix
jupyter nbextension enable rise  --py --sys-prefix

#WYSIWYG editor
jupyter nbextension install jupyter_wysiwyg  --py --sys-prefix
jupyter nbextension enable jupyter_wysiwyg --py --sys-prefix


# Resource monitoring
jupyter serverextension enable --py nbresuse --sys-prefix
jupyter nbextension install --py nbresuse --sys-prefix
jupyter nbextension enable --py nbresuse --sys-prefix

jupyter bundlerextension enable --py wordexport.wordexport --sys-prefix
jupyter bundlerextension enable --py odszip.download --sys-prefix


#Set executable permission on start file
chmod +x ${BINDER_DIR}/start

# Log version / build date
OU_PRESENTATION=$(<.ou_presentation)

DATE=`date +%Y-%m-%d/%H:%M.%S`
echo "Version: ${OU_PRESENTATION} - build time: ${DATE}." >${CONDA_DIR}/version.txt


echo "postBuild done..."
