#!/bin/bash
set -eux
PGDATA=${PGDATA:-/home/jovyan/srv/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

chmod +x $HOME/init_db.sh
$HOME/init_db.sh
#Put an equivalent of the above in a config file: init_db.sql
#psql -U postgres postgres -f init_db.sql
#psql test < seed_db.sql


#OpenRefine
wget -q -O openrefine-2.8.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/2.8/openrefine-linux-2.8.tar.gz
mkdir -p $HOME/.openrefine
tar xzf openrefine-2.8.tar.gz -C $HOME/.openrefine
rm openrefine-2.8.tar.gz

mkdir -p $HOME/openrefine

mkdir -p $HOME/.jupyter/

#Although located in binder/,
# this bash file runs in $HOME rather than $HOME/binder
mv jupyter_notebook_config.py $HOME/.jupyter/
mv open-refine-logo.svg $HOME/.jupyter/

#Enable the OpenRefine icon in JuptyerLab desktop launcher
jupyter labextension install jupyterlab-server-proxy


#Some pre-requirements
pip install --no-cache-dir numpy
pip install --no-cache-dir scipy

pip install --no-cache-dir -r binder/requirements.txt

jupyter nbextension install accessibility_toolbar 

jupyter contrib nbextension install --sys-prefix

#Enable certain extensions from the start
jupyter nbextension enable freeze/main --sys-prefix
jupyter nbextension enable highlighter/highlighter --sys-prefix
jupyter nbextension enable spellchecker/main --sys-prefix
jupyter nbextension enable collapsible_headings/main --sys-prefix
jupyter nbextension enable codefolding/main --sys-prefix
jupyter nbextension enable rubberband/main --sys-prefix
jupyter nbextension enable exercise2/main --sys-prefix
jupyter nbextension enable python-markdown/main --sys-prefix
jupyter nbextension enable export_embedded/main --sys-prefix

jupyter nbextension enable skip-traceback/main --sys-prefix
jupyter nbextension enable hide_input/main --sys-prefix
jupyter nbextension enable init_cell/main --sys-prefix

#Accessibility
jupyter nbextension install accessibility_toolbar --sys-prefix
jupyter nbextension enable accessibility_toolbar/main

#Slideshow
jupyter nbextension install rise  --py --sys-prefix
jupyter nbextension enable rise  --py --sys-prefix

#WYSIWYG editor
jupyter nbextension install jupyter_wysiwyg  --py --sys-prefix
jupyter nbextension enable jupyter_wysiwyg --py --sys-prefix


# Resource monitoring
jupyter serverextension enable --py nbresuse --sys-prefix
jupyter nbextension install --py nbresuse --sys-prefix
jupyter nbextension enable --py nbresuse --sys-prefix

jupyter bundlerextension enable --py wordexport.wordexport --sys-prefix
jupyter bundlerextension enable --py odszip.download --sys-prefix
