#!/bin/bash
set -eux

echo "Running postBuild setup...."

#Set up postgres
echo "Set-up postgres..."

PGDATA=${PGDATA:-${CONDA_DIR}/srv/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

#Copy the initialisation files into the final container
mv init_db $CONDA_DIR/
chmod +x $CONDA_DIR/init_db/postgres/init_db.sh
$CONDA_DIR/init_db/postgres/init_db.sh
#Put an equivalent of the above in a config file: init_db.sql
#psql -U postgres postgres -f init_db.sql
#psql test < seed_db.sql

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" stop

#Set up mongodb
echo "Set up mongo...."

MONGODB_VERSION=3.6.15
MONGODB_PATH=${CONDA_DIR}/srv/mongodb-$MONGODB_VERSION
MONGODB_BASE=mongodb-linux-x86_64

#https://fastdl.mongodb.org/linux/${MONGODB_BASE}-3.6.15.tgz
wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB_VERSION}.tgz

tar -xvf ${MONGODB_BASE}-${MONGODB_VERSION}.tgz >/dev/null 
rm ${MONGODB_BASE}-${MONGODB_VERSION}.tgz
mv ${MONGODB_BASE}-${MONGODB_VERSION} ${MONGODB_PATH}

mkdir ${MONGODB_PATH}/data/db -p

#Seed mongodb
#${MONGODB_PATH}/bin/mongod --dbpath ${MONGODB_PATH}/data/db &
${MONGODB_PATH}/bin/mongod --fork --logpath /dev/stdout --dbpath ${MONGODB_PATH}/data/db

mkdir -p ./tmpdatafiles
tar xvjf ./data/small_accidents.tar.bz2 -C ./tmpdatafiles
${MONGODB_PATH}/bin/mongorestore --drop --db accidents ./tmpdatafiles/small_accidents
mongod --shutdown

rm -r ./data
rm -r ./tmpdatafiles

#Set up OpenRefine
echo "Set up OpenRefine..."
wget -q -O openrefine-2.8.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/2.8/openrefine-linux-2.8.tar.gz
mkdir -p $CONDA_DIR/openrefine
tar xzf openrefine-2.8.tar.gz -C $CONDA_DIR/openrefine
rm openrefine-2.8.tar.gz




#Although located in binder/,
# this bash file runs in $HOME rather than $HOME/binder
mv .jupyter $CONDA_DIR/

echo "Enable Jupyter server proxy extension..."
#Enable the server-proxy extension installed via conda;
# this lets us proxy OpenRefine and will
# enable the OpenRefine icon in JuptyerLab desktop launcher
jupyter labextension install jupyterlab-server-proxy


echo "Install Python requirements..."

#Some Python package pre-requirements
pip install --no-cache-dir numpy
pip install --no-cache-dir scipy

#Python requirements
pip install --no-cache-dir -r binder/requirements.txt

#Other requirements
git clone https://github.com/uclixnjupyternbaccessibility/accessibility_toolbar.git

#Install and enable extensions
echo "Enable Jupyter extensions..."

jupyter nbextension install accessibility_toolbar --sys-prefix

jupyter contrib nbextension install --sys-prefix

#Enable certain extensions from the start
jupyter nbextension enable freeze/main --sys-prefix
jupyter nbextension enable highlighter/highlighter --sys-prefix
jupyter nbextension enable spellchecker/main --sys-prefix
jupyter nbextension enable collapsible_headings/main --sys-prefix
jupyter nbextension enable codefolding/main --sys-prefix
jupyter nbextension enable rubberband/main --sys-prefix
jupyter nbextension enable exercise2/main --sys-prefix
jupyter nbextension enable python-markdown/main --sys-prefix
jupyter nbextension enable export_embedded/main --sys-prefix

jupyter nbextension enable skip-traceback/main --sys-prefix
jupyter nbextension enable hide_input/main --sys-prefix
jupyter nbextension enable init_cell/main --sys-prefix

#Accessibility
jupyter nbextension install accessibility_toolbar --sys-prefix
jupyter nbextension enable accessibility_toolbar/main

#Slideshow
jupyter nbextension install rise  --py --sys-prefix
jupyter nbextension enable rise  --py --sys-prefix

#WYSIWYG editor
jupyter nbextension install jupyter_wysiwyg  --py --sys-prefix
jupyter nbextension enable jupyter_wysiwyg --py --sys-prefix


# Resource monitoring
jupyter serverextension enable --py nbresuse --sys-prefix
jupyter nbextension install --py nbresuse --sys-prefix
jupyter nbextension enable --py nbresuse --sys-prefix

jupyter bundlerextension enable --py wordexport.wordexport --sys-prefix
jupyter bundlerextension enable --py odszip.download --sys-prefix

echo "postBuild done..."

